CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE workspaces (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES workspaces(id), email text NOT NULL, name text NOT NULL, UNIQUE (workspace_id, email));
CREATE TABLE imports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), user_id uuid NOT NULL REFERENCES users(id), filename text NOT NULL, object_key text NOT NULL UNIQUE, status text NOT NULL DEFAULT 'uploaded' CHECK (status IN ('uploaded','mapping','queued','processing','completed','failed')), total_rows integer NOT NULL DEFAULT 0, processed_rows integer NOT NULL DEFAULT 0, successful_rows integer NOT NULL DEFAULT 0, failed_rows integer NOT NULL DEFAULT 0, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE import_mappings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), import_id uuid NOT NULL REFERENCES imports(id) ON DELETE CASCADE, source_column text NOT NULL, target_field text NOT NULL, UNIQUE (import_id, source_column));
CREATE TABLE import_rows (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), import_id uuid NOT NULL REFERENCES imports(id) ON DELETE CASCADE, row_number integer NOT NULL, source_data jsonb NOT NULL, normalized_data jsonb, status text NOT NULL CHECK (status IN ('pending','valid','invalid','imported')), UNIQUE (import_id, row_number));
CREATE TABLE import_errors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), import_id uuid NOT NULL REFERENCES imports(id) ON DELETE CASCADE, row_number integer NOT NULL, field text, source_value text, message text NOT NULL);
CREATE TABLE imported_records (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id), import_id uuid NOT NULL REFERENCES imports(id), source_row_number integer NOT NULL, data jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (import_id, source_row_number));
CREATE INDEX imports_progress_idx ON imports (workspace_id, status, created_at DESC);
